version: '3'

services:
  database:
    container_name: db
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 9662
      POSTGRES_DB: test4
    volumes:
      - /c/git/pgcontainer:/var/lib/postgresql/data

  java:
    container_name: app
    image: spring-university
    links:
     - "database"
    ports:
      - 8081:8081

  js:
    container_name: js_ui
    image: ui:latest
    ports:
      - 8080:8080
    links:
      - "java"